apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service-cs100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service-cs100
  template:
    metadata:
      labels:
        app: worker-service-cs100
        aadpodidbinding: aks_mi_label
    spec:
      containers:
      - name: worker-service-cs100
        image: c2dtest3contreg.azurecr.io/worker-service-cs:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"